### DISCUSSION TITLE
add to calendar and to do automations

### DISCUSSION THREAD

**Discussion by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#275] [Show and tell]
Believe we never got around to importing the complete list eg Mijn Afvalwijzer creates per year, but I made these 2 simple automations that add new dates to the calendar, and a todo for each waste pickup.

Please have a look and see it if is useful/can be optimized (I am not a heavy calendar user in HA, and this was my first effort really:

I did not yet update an automatic dismissal, which probably could be done just as easily, based on the button we already use in the Dashboard and is in the example setup.

```
automation:

  - id: afvalwijzer_in_calendar
    trigger:
      platform: state
      entity_id:
        - sensor.afvalwijzer_gft
        - sensor.afvalwijzer_papier
        - sensor.afvalwijzer_plastic
        - sensor.afvalwijzer_restafval
      not_to: &un
        - unavailable
        - unknown
      not_from: *un
#     condition:
#       >
#         {{trigger.to_state.state != trigger.from_state.state}}
    action:
      - variables:
          date: >
            {{trigger.to_state.state}}
      - service: calendar.create_event
        target:
          entity_id: calendar.afvalwijzer
        data:
          summary: Ophaaldag Saver
          description: >
            {{trigger.to_state.attributes.friendly_name}}
          start_date: >
            {{date}}
          end_date: >
            {{(as_datetime(date)+ timedelta(days=1))
               |as_timestamp|timestamp_custom('%Y-%m-%d')}}
# {{(as_datetime(date)+ timedelta(days=1)).strftime('%Y-%m-%d')}}
      - condition: state
        entity_id: input_boolean.notify_developing
        state: 'on'
      - service: notify.mobile_app_marijn
        data:
          title: Nieuwe data Afvalwijzer
          message: >
            Nieuwe data in kalender gezet voor
             {{trigger.to_state.attributes.friendly_name}}
            Op {{trigger.to_state.state}}

  - id: create_todo_from_afvalwijzer_calendar
    trigger:
      - platform: calendar
        entity_id: calendar.afvalwijzer
        event: start
        offset: -06:00:00
# dont use both, like this, they create a double todo, which both need to be dismissed
#       - platform: calendar
#         entity_id: calendar.afvalwijzer
#         event: start
#         offset: 07:00:00
    condition: []
    action:
      - service: todo.add_item
        target:
          entity_id: todo.huishouden
        data:
          item: &item
            >
              Opgelet: {{trigger.calendar_event.description}} aan de straat zetten.
          due_date: &moment
            >
              {{trigger.calendar_event.start}}

      - service: notify.mobile_app_marijn
        data:
          title: *moment
          message: *item
```
