### DISCUSSION TITLE
Can someone help a new guy making a card?

### DISCUSSION THREAD

**Discussion by GelmirTelrunya** [xirixiz/homeassistant-afvalwijzer#372] [Q&A]
I'm rather new at Home Assistant, and need some help making cards.
I installed Afvalwijzer through HACS, and I have all the sensors working now. When I go to Settings > Devices & Services and click on the 9 entities under Afvalwijzer, they do show correct dates for when various kinds of trash will be picked up.
But now I'm completely lost. What do I do with these sensors to create a card? Explain it to me like I'm in kindergarden. :P (mag ook in het Nederlands)
Thanks in advance.
Wouter.

**Comment by schijven** [comment]
Hi Wouter,

With the sensors, you can present the items in a dashbord. Go to 'Overzicht' and click on the pensol
![afbeelding](https://github.com/user-attachments/assets/1a52e80e-a8c4-4ad5-b023-dc707c0e6b3b)
Now you are in the edit mode. Click on 'Kaart toevoegen'
![afbeelding](https://github.com/user-attachments/assets/32bea089-1707-4e88-99e1-8746ee3e76a9)
en selecteer Entiteiten
![afbeelding](https://github.com/user-attachments/assets/b2175e58-9c5f-4b15-998c-80fc5bfb8846)
Here you can select the sensors. It can look like this:
![afbeelding](https://github.com/user-attachments/assets/a7433e6a-ba69-4eb3-8747-7a478986e997)
unforunately the intergration is broken for me. I hoop this is the info you are looking for

**Comment by GelmirTelrunya** [comment]
Thanks, that helped! :D
![Schermafdruk 2024-12-30 15 19 14](https://github.com/user-attachments/assets/8221c1e7-bc31-44b9-97eb-0957797492b7)

**Comment by Bolten88** [comment]
Can't i add it to a dashboard like this?

<img width="514" height="501" alt="image" src="https://github.com/user-attachments/assets/c270151d-f3b7-41e2-97e9-cc89529fa56d" />

**Reply by GelmirTelrunya** [reply]
I've been struggling with that as well, but kinda gave up... I can't make that work.
Mostly posting this reply so I'll see it if someone does offer a good explanation...

**Reply by rikvdelzen1** [reply]
> Can't i add it to a dashboard like this?
> 
> <img alt="image" width="514" height="501" src="https://private-user-images.githubusercontent.com/71372668/475007884-c270151d-f3b7-41e2-97e9-cc89529fa56d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUxNjI4MzksIm5iZiI6MTc1NTE2MjUzOSwicGF0aCI6Ii83MTM3MjY2OC80NzUwMDc4ODQtYzI3MDE1MWQtZjNiNy00MWUyLTk3ZTktY2M4OTUyOWZhNTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODE0VDA5MDg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NWFkMWM3ZDg2NGY4MzZmMmFlZWZmNDA3YzZhODU3YzVjYzc1ZmU1NjIxMDlhYWZiZDQxYzQxYjY5ZGQyMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H2nm16S4GzVkLuYs889QgvJwqa5o_A0NWyI2ZWVLhEg">

Dit kan zeker, en is eigenlijk niet heel moeilijk. Ik heb zelf een uitgebreide versie gemaakt (met behulp van ChatGPT) maar het kan natuurlijk wel makkelijker.
Bij mij wordt met een automatisering elke nacht om 00:01 gekeken of er vandaag een bepaalde afvalsoort opgehaald wordt, als dat zo is dan wordt er een boolean op 'on' gezet, dit is dus allemaal aangepast naar mijn wensen, en dus anders dan standaard. Die boolean switches worden dan om 00:01 de dag erna uitgezet, behalve die van papier omdat ik die pas een dag later binnenhaal (m'n meldingen om afval binnen te halen zijn ook gebaseerd op die boolean switches). Mijn script in m'n dashboard kijkt naar of de status 'On' is, als dat zo is dan staat er vandaag, is dat niet zo dan staat de datum er (of Morgen / Overmorgen).

Mijn code kun je dus zeker niet volledig gebruiken, maar je zou het wel als eerste input kunnen gebruiken als je bijvoorbeeld hulp vraagt van chatgpt. Kijk ook vooral even in mijn topic wat ik aangemaakt had, daarin geef ik nog veel meer aan 

```type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        entity: sensor.afvalwijzer_gft
        name: GFT
        icon: mdi:food-apple
        show_state: true
        state_display: |
          [[[ 
            if (!entity.state) return '—'; 
            const datum = new Date(entity.state); 
            const vandaag = new Date(); 
            const morgen = new Date(); 
            morgen.setDate(vandaag.getDate() + 1); 
            const overmorgen = new Date(); 
            overmorgen.setDate(vandaag.getDate() + 2); 
            const isZelfdeDag = (d1, d2) => d1.toDateString() === d2.toDateString();
            
            const today_boolean = states['input_boolean.afval_gft_ophalen'].state === 'on';
            if (today_boolean) return 'Vandaag';
            
            if (isZelfdeDag(datum, morgen)) return 'Morgen'; 
            if (isZelfdeDag(datum, overmorgen)) return 'Overmorgen'; 
            return datum.toLocaleDateString('nl-NL'); 
          ]]]
        styles:
          card:
            - background-color: "#b4e197"
            - color: black
          icon:
            - color: green
          name:
            - font-weight: bold
          state:
            - font-size: 14px
      - type: custom:button-card
        entity: sensor.afvalwijzer_pmd
        name: Plastic
        icon: mdi:recycle
        show_state: true
        state_display: |
          [[[ 
            if (!entity.state) return '—'; 
            const datum = new Date(entity.state); 
            const vandaag = new Date(); 
            const morgen = new Date(); 
            morgen.setDate(vandaag.getDate() + 1); 
            const overmorgen = new Date(); 
            overmorgen.setDate(vandaag.getDate() + 2); 
            const isZelfdeDag = (d1, d2) => d1.toDateString() === d2.toDateString();
            
            const today_boolean = states['input_boolean.afval_pmd_ophalen'].state === 'on';
            if (today_boolean) return 'Vandaag';
            
            if (isZelfdeDag(datum, morgen)) return 'Morgen'; 
            if (isZelfdeDag(datum, overmorgen)) return 'Overmorgen'; 
            return datum.toLocaleDateString('nl-NL'); 
          ]]]
        styles:
          card:
            - background-color: "#fdb649"
            - color: black
          icon:
            - color: "#b35c00"
          name:
            - font-weight: bold
          state:
            - font-size: 14px
      - type: custom:button-card
        entity: sensor.afvalwijzer_restafval
        name: Restafval
        icon: mdi:trash-can
        show_state: true
        state_display: |
          [[[ 
            if (!entity.state) return '—'; 
            const datum = new Date(entity.state); 
            const vandaag = new Date(); 
            const morgen = new Date(); 
            morgen.setDate(vandaag.getDate() + 1); 
            const overmorgen = new Date(); 
            overmorgen.setDate(vandaag.getDate() + 2); 
            const isZelfdeDag = (d1, d2) => d1.toDateString() === d2.toDateString();
            
            const today_boolean = states['input_boolean.afval_rest_ophalen'].state === 'on';
            if (today_boolean) return 'Vandaag';
            
            if (isZelfdeDag(datum, morgen)) return 'Morgen'; 
            if (isZelfdeDag(datum, overmorgen)) return 'Overmorgen'; 
            return datum.toLocaleDateString('nl-NL'); 
          ]]]
        styles:
          card:
            - background-color: "#b0b0b0"
            - color: black
          icon:
            - color: "#6e6e6e"
          name:
            - font-weight: bold
          state:
            - font-size: 14px
      - type: custom:button-card
        entity: sensor.afvalwijzer_papier
        name: Papier
        icon: mdi:file-document
        show_state: true
        state_display: |
          [[[ 
            if (!entity.state) return '—'; 
            const datum = new Date(entity.state); 
            const vandaag = new Date(); 
            const morgen = new Date(); 
            morgen.setDate(vandaag.getDate() + 1); 
            const overmorgen = new Date(); 
            overmorgen.setDate(vandaag.getDate() + 2); 
            const isZelfdeDag = (d1, d2) => d1.toDateString() === d2.toDateString();
            
            const paper_boolean = states['input_boolean.afval_papier_ophalen'].state === 'on';
            const paper_last_changed = new Date(states['input_boolean.afval_papier_ophalen'].last_changed);
            const today_boolean = paper_boolean && paper_last_changed.toDateString() === vandaag.toDateString();
            
            if (today_boolean) return 'Vandaag';
            
            if (isZelfdeDag(datum, morgen)) return 'Morgen'; 
            if (isZelfdeDag(datum, overmorgen)) return 'Overmorgen'; 
            return datum.toLocaleDateString('nl-NL'); 
          ]]]
        styles:
          card:
            - background-color: "#7ec8e3"
            - color: black
          icon:
            - color: "#4a90e2"
          name:
            - font-weight: bold
          state:
            - font-size: 14px
  - type: entities
    entities:
      - type: custom:template-entity-row
        entity: sensor.afvalwijzer_next_type
        name: Volgende afvalsoort
        state: >
          {% set s = states('sensor.afvalwijzer_next_type') %} {% if s in
          ['unknown', 'unavailable', '', None] %}
            Onbekend
          {% else %}
            {% set types = s.split(',') | map('trim') | list %}
            {% set mapped = types | map('lower') 
                | map('replace', 'papier','Papier') 
                | map('replace', 'gft','GFT') 
                | map('replace', 'restafval','Restafval') 
                | map('replace', 'pmd','Plastic') | list %}
            {{ mapped | join(' & ') }}
          {% endif %}
      - type: custom:template-entity-row
        entity: sensor.afvalwijzer_secondary_gft
        name: GFT reiniging
        state: >
          {% set d = states('sensor.afvalwijzer_secondary_gft') %} {% set
          today_boolean = states('input_boolean.afval_gft_schoonmaken') == 'on'
          %} {% if today_boolean %}
            Vandaag
          {% elif d not in ['unknown', 'unavailable', '', None] %}
            {% set dt = as_datetime(d) %}
            {% set vandaag = now().date() %}
            {% set morgen = vandaag + timedelta(days=1) %}
            {% set overmorgen = vandaag + timedelta(days=2) %}
            {% set maanden = ['januari', 'februari', 'maart', 'april', 'mei', 'juni', 'juli', 'augustus', 'september', 'oktober', 'november', 'december'] %}
            {% if dt.date() == morgen %} Morgen
            {% elif dt.date() == overmorgen %} Overmorgen
            {% else %} {{ dt.day }} {{ maanden[dt.month - 1] }} {{ dt.year }}
            {% endif %}
          {% else %} {{- '' -}} {% endif %}
        style: >
          {% if states('sensor.afvalwijzer_secondary_gft') in ['unknown',
          'unavailable', '', None] %}
            display: none;
          {% endif %}
```

Visueel ziet dit er zo uit:
<img width="529" height="283" alt="image" src="https://github.com/user-attachments/assets/dd0ee80f-ab37-4081-bbcf-94ff0c647f98" />


Je mag mij altijd een berichtje sturen als je vragen hebt over hoe dit werkt.

**Reply by D-Jakke** [reply]
Krijg het niet voor elkaar om zulke kaart te maken :-(

**Comment by xirixiz** [comment]
Dit is de code die ik zelf gebruik:

Het belangrijkste is zorgen dat je de images hebt in ```config/www/afvalwijzer/```
En uiteraarde dat de sensoren (entities) ook echt bestaan (dus op de naamgeving letten dat het overeenkomt met jouw situatie).

De images kan je wel in de community vinden, of anders kan ik er wel een aantal delen in de repo.

```
type: custom:stack-in-card
cards:
  - type: horizontal-stack
    cards:
      - type: picture-entity
        entity: sensor.afvalwijzer_today_formatted
        show_name: false
        show_state: false
        state_image:
          GFT: /local/afvalwijzer/GFT.png
          Geen: /local/afvalwijzer/Geen.png
          PMD: /local/afvalwijzer/PMD.png
          Papier: /local/afvalwijzer/Papier.png
          Restafval: /local/afvalwijzer/Restafval.png
      - type: picture-entity
        entity: sensor.afvalwijzer_tomorrow_formatted
        show_name: false
        show_state: false
        state_image:
          GFT: /local/afvalwijzer/GFT.png
          Geen: /local/afvalwijzer/Geen.png
          PMD: /local/afvalwijzer/PMD.png
          Papier: /local/afvalwijzer/Papier.png
          Restafval: /local/afvalwijzer/Restafval.png
      - type: picture-entity
        entity: sensor.afvalwijzer_day_after_tomorrow_formatted
        show_name: false
        show_state: false
        state_image:
          GFT: /local/afvalwijzer/GFT.png
          Geen: /local/afvalwijzer/Geen.png
          PMD: /local/afvalwijzer/PMD.png
          Papier: /local/afvalwijzer/Papier.png
          Restafval: /local/afvalwijzer/Restafval.png
  - type: custom:auto-entities
    card:
      type: glance
    filter:
      exclude:
        - entity_id: sensor.afvalwijzer_*next*
        - entity_id: sensor.afvalwijzer_day_after_tomorrow*
        - entity_id: sensor.afvalwijzer_today*
        - entity_id: sensor.afvalwijzer_tomorrow*
        - entity_id: sensor.afvalwijzer_kerstbomen*
        - entity_id: sensor.afvalwijzer_*orgen
        - entity_id: sensor.afvalwijzer_van*
      include:
        - entity_id: sensor.afvalwijzer_*_formatted
          options:
            format: date
    sort:
      method: state
  - type: markdown
    content: >-
      <center>De volgende leging is {{ states('sensor.afvalwijzer_next_type')
      }}. Dat is over {{ states('sensor.afvalwijzer_next_in_days') }} {% if
      is_state('sensor.afvalwijzer_next_in_days', '1') %}dag{% else %}dagen{%
      endif %}.</center>
  - type: entities
    show_header_toggle: false
    state_color: false
    entities:
      - entity: input_boolean.waste_moved
      - entity: input_boolean.waste_reminder
```

Dit zijn de sensoren die ik zelf aanmaak in een package file
```
template:
  - sensor:
      - name: Afvalwijzer GFT formatted
        unique_id: afvalwijzer_gft_formatted
        state: >-
          {% set ts = states('sensor.afvalwijzer_gft') | as_timestamp(default=none) %}
          {{ ts | timestamp_custom('%d-%m-%Y') if ts is not none else 'Geen' }}

      - name: Afvalwijzer Papier formatted
        unique_id: afvalwijzer_papier_formatted
        state: >-
          {% set ts = states('sensor.afvalwijzer_papier') | as_timestamp(default=none) %}
          {{ ts | timestamp_custom('%d-%m-%Y') if ts is not none else 'Geen' }}

      - name: Afvalwijzer PMD formatted
        unique_id: afvalwijzer_pmd_formatted
        state: >-
          {% set ts = states('sensor.afvalwijzer_pmd') | as_timestamp(default=none) %}
          {{ ts | timestamp_custom('%d-%m-%Y') if ts is not none else 'Geen' }}

      - name: Afvalwijzer Restafval formatted
        unique_id: afvalwijzer_restafval_formatted
        state: >-
          {% set ts = states('sensor.afvalwijzer_restafval') | as_timestamp(default=none) %}
          {{ ts | timestamp_custom('%d-%m-%Y') if ts is not none else 'Geen' }}

      - name: Afvalwijzer next item formatted
        unique_id: afvalwijzer_next_item_formatted
        state: >-
          {{ {
            'gft': 'GFT',
            'papier': 'Papier',
            'pmd': 'PMD',
            'restafval': 'Restafval'
          }.get(states('sensor.afvalwijzer_next_item'), 'Geen') }}

      - name: Afvalwijzer today formatted
        unique_id: afvalwijzer_today_formatted
        state: >-
          {{ {
            'gft': 'GFT',
            'papier': 'Papier',
            'pmd': 'PMD',
            'restafval': 'Restafval'
          }.get(states('sensor.afvalwijzer_today'), 'Geen') }}

      - name: Afvalwijzer tomorrow formatted
        unique_id: afvalwijzer_tomorrow_formatted
        state: >-
          {{ {
            'gft': 'GFT',
            'papier': 'Papier',
            'pmd': 'PMD',
            'restafval': 'Restafval'
          }.get(states('sensor.afvalwijzer_tomorrow'), 'Geen') }}

      - name: Afvalwijzer day after tomorrow formatted
        unique_id: afvalwijzer_day_after_tomorrow_formatted
        state: >-
          {{ {
            'gft': 'GFT',
            'papier': 'Papier',
            'pmd': 'PMD',
            'restafval': 'Restafval'
          }.get(states('sensor.afvalwijzer_day_after_tomorrow'), 'Geen') }}
```
