### ISSUE TITLE
Doe ik iets fout?

### ISSUE THREAD

**Issue by JeroenSchwab** [xirixiz/homeassistant-afvalwijzer#108]
Ik heb onlangs de afvalwijzer in home assistant geinstalleerd en dit
werkte prima (zonder notifications trouwens) echter krijg ik nu in eens
een foutmelding als ik mijn config check.

fout melding: bad indentation of a mapping entry at line 33, column 3:
      - type: 'custom:auto-entities'

dit staat er vanaf line 33 in mijn configureration.yaml:

```
   - type: 'custom:auto-entities'
     card:
       type: glance
     filter:
       include:
         - entity_id: sensor.afvalwijzer_gft
         - entity_id: sensor.afvalwijzer_papier
#        - entity_id: sensor.afvalwijzer_pmd
         - entity_id: sensor.afvalwijzer_restafval
     sort:
       attribute: days_until_collection_date
       method: attribute
       numeric: true
```

ik heb niets aan mijn config veranderd en heb al gekeken of de
indentation niet goed is met yamllint maar dat is allemaal goed.

Ik vroeg mij tevens af hoe ik de mooie icoontjes in HA krijg heb al gezocht op de HA website maar kan daar niets vinden.

**Comment by xirixiz** [comment]
Probeer dit eens ... oke een deel zal niet werken, maar verwacht toch een foutieve uitlijning ergens.

```
cards:
  - entities:
      - sensor.moon
    show_header_toggle: false
    type: entities
  - entity: weather.home
    name: Thuis
    type: weather-forecast
  - cards:
      - entity: sensor.afvalwijzer_today_formatted
        show_name: false
        show_state: false
        state_image:
          GFT: /local/afvalwijzer/GFT.png
          Geen: /local/afvalwijzer/Geen.png
          PMD: /local/afvalwijzer/PMD.png
          Papier: /local/afvalwijzer/Papier.png
          Restafval: /local/afvalwijzer/Restafval.png
        type: picture-entity
      - entity: sensor.afvalwijzer_tomorrow_formatted
        show_name: false
        show_state: false
        state_image:
          GFT: /local/afvalwijzer/GFT.png
          Geen: /local/afvalwijzer/Geen.png
          PMD: /local/afvalwijzer/PMD.png
          Papier: /local/afvalwijzer/Papier.png
          Restafval: /local/afvalwijzer/Restafval.png
        type: picture-entity
      - entity: sensor.afvalwijzer_day_after_tomorrow_formatted
        show_name: false
        show_state: false
        state_image:
          GFT: /local/afvalwijzer/GFT.png
          Geen: /local/afvalwijzer/Geen.png
          PMD: /local/afvalwijzer/PMD.png
          Papier: /local/afvalwijzer/Papier.png
          Restafval: /local/afvalwijzer/Restafval.png
        type: picture-entity
    type: horizontal-stack
  - type: 'custom:auto-entities'
    card:
      type: glance
    filter:
      include:
        - entity_id: sensor.afvalwijzer_gft
        - entity_id: sensor.afvalwijzer_papier
        - entity_id: sensor.afvalwijzer_pmd
        - entity_id: sensor.afvalwijzer_restafval
    sort:
      attribute: days_until_collection_date
      method: attribute
      numeric: true
  - entities:
      - sensor.afvalwijzer_next_item_formatted
      - style:
          background: '#62717b'
          height: 1px
          margin-left: auto
          margin-right: auto
        type: divider
      - input_boolean.waste_moved
      - input_boolean.waste_reminder
    show_header_toggle: false
    type: entities
type: vertical-stack
```

**Comment by JeroenSchwab** [comment]
Ik heb bovenstaande in mijn configuration.yaml geprobeerd maar krijg nu een nieuwe fout melding:
Component error: type - Integration 'type' not found.
Component error: cards - Integration 'cards' not found.

**Comment by JeroenSchwab** [comment]
Ik heb ook een yaml check gedaan via de site die je aan geeft heb mijn hele configuration.yaml nagekeken en is goed.

**Comment by Mariusthvdb** [comment]
wat is de rest van je configuratie? als je de hele card post kunnen we dat beter bekijken.

**Comment by JeroenSchwab** [comment]
Ik heb dit:
- type: 'custom:auto-entities'
     card:
       type: glance
     filter:
       include:
         - entity_id: sensor.afvalwijzer_gft
         - entity_id: sensor.afvalwijzer_papier
#        - entity_id: sensor.afvalwijzer_pmd
         - entity_id: sensor.afvalwijzer_restafval
     sort:
       attribute: days_until_collection_date
       method: attribute
       numeric: true

in mijn configuration.yaml gezet en toen een herstart gedaan.
vervolgens kon ik een Glance Card maken via de overview pagina en het werkte.
Vervolgens nog een herstart gedaan waarna het niet meer werkte.

Wat ik niet snap omdat ik verder niets heb veranderd in de tussen tijd.
Mijn configuration.yaml:
`
homeassistant:
  customize: !include customize.yaml
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
#light: !include lights.yaml

# Text to speech
tts:
  - platform: google_translate

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

default_config:
system_health:
hassio:
config:

mqtt:
  broker: 192.168.30.5
`

**Comment by Mariusthvdb** [comment]
maak er even een goed geformatteerd code block van, dan kunnen we de yaml goed beoordelen.

ofwel met de <> insert code in de menubalk van je edit window, ofwel door voor en na de yaml 3 backticks te zetten:

```
hier tussen staat code
```

**Comment by JeroenSchwab** [comment]
Dat heb ik gedaan maar zie nu dat het niet goed in beeld komt. Heb het net nog eens geprobeerd maar hij wil het niet goed weer geven. Sorry. Heb nu handmatig de code maar tussen <pre><code></code></pre> gezet.

**Comment by Mariusthvdb** [comment]
de hele yaml tekst selecteren en dan op <> klikken in the taakbalk. -----------------^

**Comment by ronaldvandervegt** [comment]
@JeroenSchwab In mijn code staat precies hetzelfde als in jouw code, en die werkt bij mij:
```
- type: 'custom:auto-entities'
  card:
    type: glance
  filter:
    include:
      - entity_id: sensor.afvalwijzer_gft
      - entity_id: sensor.afvalwijzer_papier
      - entity_id: sensor.afvalwijzer_pmd
      - entity_id: sensor.afvalwijzer_restafval
  sort:
    attribute: days_until_collection_date
    method: attribute
    numeric: true
```
Tenminste: ik heb jouw code even in de Prettify YAML tool gezet, en kreeg toen wel meldingen van 'bad indentation'. Dus ik zou je aanraden om daar even heel goed naar te kijken.

**Comment by JeroenSchwab** [comment]
@ronaldvandervegt bij mij werkte het dus ook en ik heb inderdaad goed gekeken naar de indentation (met yamllint en de link hier boven) en die moet goed zijn. Ik heb zelfs mijn hele yaml config gecontroleerd omdat het ook nog wel eens voor komt dat er ergens anders (eerder) nog een fout in staat maar dat is ook goed. Ik vraag niet snel om hulp altijd eerst zelf proberen en uitzoeken vind ik. Maar hier kom ik niet uit.

**Comment by Mariusthvdb** [comment]
het probleem is toch duidelijk, en in je eigen post https://github.com/xirixiz/homeassistant-afvalwijzer/issues/108#issuecomment-714759840 staat de verkeerde spacing overduidelijk in beeld.

terwijl ik 1 post daarboven de goede yaml code heb gepost...

**Comment by JeroenSchwab** [comment]
> het probleem is toch duidelijk, en in je eigen post [#108 (comment)](https://github.com/xirixiz/homeassistant-afvalwijzer/issues/108#issuecomment-714759840) staat de verkeerde spacing overduidelijk in beeld.
> 
> terwijl ik 1[ post daarboven](https://github.com/xirixiz/homeassistant-afvalwijzer/issues/108#issuecomment-714736321) de goede yaml code heb gepost...

Ik heb het er in staan als de code in je post ook met "- type:  recht boven card:" de post hier klopt inderdaad niet.

**Comment by JeroenSchwab** [comment]
Ik heb het nog maals geprobeerd maar blijf fout meldingen krijgen.

> Probeer dit eens ... oke een deel zal niet werken, maar verwacht toch een foutieve uitlijning ergens.
> 
> Of probeer de hele code van de yaml hier eens te "fixen": https://onlineyamltools.com/prettify-yaml
> 
> ```
> cards:
>   - entities:
>       - sensor.moon
>     show_header_toggle: false
>     type: entities
>   - entity: weather.home
>     name: Thuis
>     type: weather-forecast
>   - cards:
>       - entity: sensor.afvalwijzer_today_formatted
>         show_name: false
>         show_state: false
>         state_image:
>           GFT: /local/afvalwijzer/GFT.png
>           Geen: /local/afvalwijzer/Geen.png
>           PMD: /local/afvalwijzer/PMD.png
>           Papier: /local/afvalwijzer/Papier.png
>           Restafval: /local/afvalwijzer/Restafval.png
>         type: picture-entity
>       - entity: sensor.afvalwijzer_tomorrow_formatted
>         show_name: false
>         show_state: false
>         state_image:
>           GFT: /local/afvalwijzer/GFT.png
>           Geen: /local/afvalwijzer/Geen.png
>           PMD: /local/afvalwijzer/PMD.png
>           Papier: /local/afvalwijzer/Papier.png
>           Restafval: /local/afvalwijzer/Restafval.png
>         type: picture-entity
>       - entity: sensor.afvalwijzer_day_after_tomorrow_formatted
>         show_name: false
>         show_state: false
>         state_image:
>           GFT: /local/afvalwijzer/GFT.png
>           Geen: /local/afvalwijzer/Geen.png
>           PMD: /local/afvalwijzer/PMD.png
>           Papier: /local/afvalwijzer/Papier.png
>           Restafval: /local/afvalwijzer/Restafval.png
>         type: picture-entity
>     type: horizontal-stack
>   - type: 'custom:auto-entities'
>     card:
>       type: glance
>     filter:
>       include:
>         - entity_id: sensor.afvalwijzer_gft
>         - entity_id: sensor.afvalwijzer_papier
>         - entity_id: sensor.afvalwijzer_pmd
>         - entity_id: sensor.afvalwijzer_restafval
>     sort:
>       attribute: days_until_collection_date
>       method: attribute
>       numeric: true
>   - entities:
>       - sensor.afvalwijzer_next_item_formatted
>       - style:
>           background: '#62717b'
>           height: 1px
>           margin-left: auto
>           margin-right: auto
>         type: divider
>       - input_boolean.waste_moved
>       - input_boolean.waste_reminder
>     show_header_toggle: false
>     type: entities
> type: vertical-stack
> ```

Als ik het er op bovenstaande manier in zet krijg ik een foutmelding dat de integratie card niet bestaat.
Als ik het er op onderstaande manier in zet krijg ik een fout dat de integratie type niet bestaat.


> @JeroenSchwab In mijn code staat precies hetzelfde als in jouw code, en die werkt bij mij:
> 
> ```
> - type: 'custom:auto-entities'
>   card:
>     type: glance
>   filter:
>     include:
>       - entity_id: sensor.afvalwijzer_gft
>       - entity_id: sensor.afvalwijzer_papier
>       - entity_id: sensor.afvalwijzer_pmd
>       - entity_id: sensor.afvalwijzer_restafval
>   sort:
>     attribute: days_until_collection_date
>     method: attribute
>     numeric: true
> ```
> 
> Tenminste: ik heb jouw code even in de Prettify YAML tool gezet, en kreeg toen wel meldingen van 'bad indentation'. Dus ik zou je aanraden om daar even heel goed naar te kijken.

**Comment by Mariusthvdb** [comment]
mss moet je eens met een lege view beginnen en alleen de meest compacte code proberen, alleen de glance card doe je hierboven plaatst.

altijd goed om code te testen in een geïsoleerde omgeving. gewoon een eigen test view aanmaken. en dan hier de code posten, in correct geformatteerde codeblocks. het lijkt er toch het op dat je steeds niet de goede yaml probeert.

> expected at line 11, column 1:

column 1, dat is de eerste positie in de tekst, dat klopt gewoon niet. In welke view heb je dat zo staan?

**Comment by JeroenSchwab** [comment]
> mss moet je eens met een lege view beginnen en alleen de meest compacte code proberen, alleen de glance card doe je hierboven plaatst.
> 
> altijd goed om code te testen in een geïsoleerde omgeving. gewoon een eigen test view aanmaken. en dan hier de code posten, in correct geformatteerde codeblocks. het lijkt er toch het op dat je steeds niet de goede yaml probeert.
> 
> > expected at line 11, column 1:
> 
> column 1, dat is de eerste positie in de tekst, dat klopt gewoon niet. In welke view heb je dat zo staan?

Ik check alles 3 keer met verschillende tools om de yaml te controleren. Ik Kopieer mijn hele configuration.yaml incl. de code voor de afvalwijzer en dat is allemaal goed. ik krijg het idee dat de config checker van HA niet goed werkt.

**Comment by Mariusthvdb** [comment]
Luister, je blijft volharden dat je yaml correct is terwijl je nog niet 1 keer een correct code block hebt gepost.

Daarbij komt dat correct Yaml een erg foute config kan zijn, dus die check zegt niet alles.

Er hebben hier nu 3 mensen suggesties gedaan en je wilt dat kennelijk niet proberen.

Dan houdt het natuurlijk wel een beetje op.

Zonder een minimale view die je fout oplevert kunnen we niets.

**Comment by xirixiz** [comment]
Daar sluit ik mij bij aan. Bedenk ook dat er geen enkele andere melding is omtrent deze fout, dus is het meer dan zeer onwaarschijnlijk dat er een ander probleem is dan home assistant aangeeft.

Begin simpel en plaats 1 sensor op je lovelace ui en ga van daaruit verder.

**Comment by JeroenSchwab** [comment]
> Luister, je blijft volharden dat je yaml correct is terwijl je nog niet 1 keer een correct code block hebt gepost.
> 
> Daarbij komt dat correct Yaml een erg foute config kan zijn, dus die check zegt niet alles.
> 
> Er hebben hier nu 3 mensen suggesties gedaan en je wilt dat kennelijk niet proberen.
> 
> Dan houdt het natuurlijk wel een beetje op.
> 
> Zonder een minimale view die je fout oplevert kunnen we niets.

@Mariusthvdb Sorry hoor maar als je aangeeft dat ik nog geen 1 keer een correct code block heb gepost dan moet je even terug lezen in de eerder posts.
Ik ben het met je eens dat een check niet alles zegt maar hoe kan ik mijn yaml anders controleren dan te vertrouwen op de tools die er te vinden zijn? 
Ik heb alle suggesties geprobeerd en ik krijg het niet aan de praat. ik heb zelf home assistant al eens opniet geinstalleerd op een nieuwe Raspberry pi dus de bewering dat ik het niet probeer is dikke onzin.
Ik heb naar mijn mening alles wat er nodig is om inzicht te geven in mijn situatie hier geplaatst.
ik denk dat ik het hier maar bij laat als de toon hier op deze manier verder gaat.

**Comment by JeroenSchwab** [comment]
> Daar sluit ik mij bij aan. Bedenk ook dat er geen enkele andere melding is omtrent deze fout, dus is het meer dan zeer onwaarschijnlijk dat er een ander probleem is dan home assistant aangeeft.
> 
> Begin simpel en plaats 1 sensor op je lovelace ui en ga van daaruit verder.

@xirixiz ik heb 1 van de sensoren geplaatst in de ui. echter het deel:
```
- type: 'custom:auto-entities'
  card:
    type: glance
  filter:
    include:
      - entity_id: sensor.afvalwijzer_gft
      - entity_id: sensor.afvalwijzer_papier
      - entity_id: sensor.afvalwijzer_pmd
      - entity_id: sensor.afvalwijzer_restafval
  sort:
    attribute: days_until_collection_date
    method: attribute
    numeric: true
```
werkt niet zodra ik dit in mijn configuration.yaml plaats krijg ik meldingen dat of de indentation niet goed is of dat de intergratie  type niet bestaat.
Het heeft gewerkt daarom snap ik niet wat er fout gaat.
Als ik namelijk de code hier boven er uit haal en dan een config check doe is alles goed.
