### ISSUE TITLE
FR change attr date of _next sensors in datetime 

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#116]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug

please consider changing the attribute date of the _next sensors into a datetime type, so we can manipulate it using the strptime and as_timestamp functions.

As it is now, it is a string we need to use different, less intelligent jinja string manipulations.

eg, I wish to not show 'Wed 18 Nov' but '18 November' (since I already show the day name in another secondary template). I could make some string manipulations, but using a datetime type would make that more robust, and also universally applicable.

```
    filter:
      include:
        - entity_id: sensor.afvalwijzer_*_next
          options:
            type: custom:template-entity-row
            state: >
              {{state_attr(config.entity,'date')[3:]}}
```

give me this:

<img width="477" alt="Schermafbeelding 2020-11-15 om 23 36 24" src="https://user-images.githubusercontent.com/33354141/99198834-6900b400-279b-11eb-83a7-e803ee9d3753.png">

but would require a full mapper to make November out of Nov. Using a datetime type would require a simple '%-d %B' timestamp_custom.

```
{{as_timestamp(state_attr(config.entity,'date')|timestamp_custom('%-d %B')}}
```
since the next_date sensor does already use this format, I would hope this to be possible.

## Debug log

```text

Add your logs here.

```
