### ISSUE TITLE
min() arg is an empty sequence

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#118]
## Version of the custom_component

5.1.2
## Configuration

```yaml

sensor:

  - platform: afvalwijzer
    provider: mijnafvalwijzer
    postal_code: !secret postcode
    street_number: !secret huisnummer
    default_label: Geen

```

## Describe the bug

all of a sudden the below error is in the logs, and the sensor.afvalwijzer_next_in_days and sensor.afvalwijzer_next_item are not created.

## Debug log

```text

Logger: custom_components.afvalwijzer.const.const
Source: custom_components/afvalwijzer/provider/afvalwijzer.py:284 
Integration: afvalwijzer (documentation, issues) 
First occurred: 11:35:55 AM (4 occurrences) 
Last logged: 1:37:57 PM

Error occurred: min() arg is an empty sequence

```
could be a server error? post it here anyways, because it might not be....
thanks for having a look
