### ISSUE TITLE
sensor.afvalwijzer_tomorrow not showing correct data

### ISSUE THREAD

**Issue by wltng** [xirixiz/homeassistant-afvalwijzer#119]
## Version of the custom_component

5.1.3
## Configuration
```yaml
- platform: afvalwijzer # Required
  provider: mijnafvalwijzer
  postal_code: !secret postcode  # Required
  street_number: !secret housenumber # Required
```

## Describe the bug
sensor.afvalwijzer_tomorrow is not showing anything even though GFT is due tomorrow
GFT days_until_collection_date is 1
- sensor.afvalwijzer_next_date is correct (1-12-2020)
- sensor.afvalwijzer_gft is correct too

Integration seems to think November has 31 days.
