### ISSUE TITLE
little problems

### ISSUE THREAD

**Issue by larsoss** [xirixiz/homeassistant-afvalwijzer#122]
I have 2 minor problems.

The first is that the image is not displayed properly. If there is no need, it will go well, but tomorrow it will be organic waste and it will not be displayed properly.

Second, the dates are not sorted. what's wrong with the code?

`type: 'custom:vertical-stack-in-card'
cards:
  - type: horizontal-stack
    cards:
      - type: picture-entity
        entity: sensor.afvalwijzer_today
        name: Vandaag
        show_state: false
        state_image:
          gft: /local/GFT.png
          papier: /local/Papier.png
          restafval: /local/Restafval3.png
          plastic: /local/Plastic.png
          Geen: /local/Geen.png
      - type: picture-entity
        entity: sensor.afvalwijzer_tomorrow
        name: Morgen
        show_state: false
        state_image:
          Gft: /local/GFT.png
          Papier: /local/Papier.png
          Restafval: /local/Restafval.png
          Plastic: /local/Plastic.png
          Geen: /local/Geen.png
  - type: glance
    entities:
      - entity: sensor.afvalwijzer_gft
        name: GFT
      - entity: sensor.afvalwijzer_papier
        name: Papier
      - entity: sensor.afvalwijzer_restafval
        name: Plastic
      - entity: sensor.afvalwijzer_plastic
        name: Restafval
    sort:
      attribute: days_until_collection_date
      method: attribute
      nummeric: true
[image](https://ibb.co/nRL0B4q)
*edit the image link

**Comment by xirixiz** [comment]
Can you please format your code? Mine is like below and it's working properly.

```
cards:
  - cards:
      - entity: sensor.afvalwijzer_today_formatted
        show_name: false
        show_state: false
        state_image:
          GFT: /local/afvalwijzer/GFT.png
          Geen: /local/afvalwijzer/Geen.png
          PMD: /local/afvalwijzer/PMD.png
          Papier: /local/afvalwijzer/Papier.png
          Restafval: /local/afvalwijzer/Restafval.png
        type: picture-entity
      - entity: sensor.afvalwijzer_tomorrow_formatted
        show_name: false
        show_state: false
        state_image:
          GFT: /local/afvalwijzer/GFT.png
          Geen: /local/afvalwijzer/Geen.png
          PMD: /local/afvalwijzer/PMD.png
          Papier: /local/afvalwijzer/Papier.png
          Restafval: /local/afvalwijzer/Restafval.png
        type: picture-entity
      - entity: sensor.afvalwijzer_day_after_tomorrow_formatted
        show_name: false
        show_state: false
        state_image:
          GFT: /local/afvalwijzer/GFT.png
          Geen: /local/afvalwijzer/Geen.png
          PMD: /local/afvalwijzer/PMD.png
          Papier: /local/afvalwijzer/Papier.png
          Restafval: /local/afvalwijzer/Restafval.png
        type: picture-entity
    type: horizontal-stack
  - type: 'custom:auto-entities'
    card:
      type: glance
    filter:
      include:
        - entity_id: sensor.afvalwijzer_gft
        - entity_id: sensor.afvalwijzer_papier
        - entity_id: sensor.afvalwijzer_pmd
        - entity_id: sensor.afvalwijzer_restafval
    sort:
      attribute: days_until_collection_date
      method: attribute
      numeric: true
  - entities:
      - entity: sensor.afvalwijzer_next_item
      - entity: sensor.afvalwijzer_next_in_days
      - style:
          background: '#62717b'
          height: 1px
          margin-left: auto
          margin-right: auto
        type: divider
      - entity: input_boolean.waste_moved
      - entity: input_boolean.waste_reminder
    show_header_toggle: false
    type: entities
type: vertical-stack
```
