### ISSUE TITLE
Werkt helaas niet voor de Rova afval kalender

### ISSUE THREAD

**Issue by RefleCs** [xirixiz/homeassistant-afvalwijzer#128]
https://inzamelkalender.rova.nl/ is eenzelfde soort site maar werkt helaas niet met deze oplossing.

**Comment by xirixiz** [comment]
Klopt! De intergratie is er wel een tijd geweest maar gebruikt niet dezelfde API helaas. Ik weet ook niet of er een API beschikbaar is van Rovi met json output. Indien die er wel is kan ik het eenvoudig toevoegen.

Er zijn overigens wel alternatieve componenten die Rova wel ondersteunen.

**Comment by xirixiz** [comment]
Helaas wel via scrapers....

**Comment by xirixiz** [comment]
Heb je wellicht een postcode en huisnummer? Mogelijk heb ik al iets gevonden om het alsnog te intergreren.

**Comment by RefleCs** [comment]
Helaas ;) tnx ik zal eens kijken of ik wat info daar vandaan kan halen. Zal er eens een mailtje aan wagen :)

**Comment by RefleCs** [comment]
ja hoor 3824XB 2

**Comment by xirixiz** [comment]
Ik kom dit namelijk tegen: https://github.com/GidoHakvoort/rova/blob/master/rova/rova.py
Mogelijk kan ik hier wel eea uit hergerbruiken en intergreren. Duik er morgen even in :).

**Comment by RefleCs** [comment]
Tnx!! Super mooie integratie dus ik zou hem graag gebruike :D kan ik de kids tenminste triggeren met popups op hun telefoons haha

**Comment by xirixiz** [comment]
Klopt de data? 

curl --cookie "RovaLc_inwoners={\"Id\":123123,\"ZipCode\":\"3824XB \",\"HouseNumber\":\"2\",\"HouseAddition\":\"\"}" https://www.rova.nl/api/TrashCalendar/GetCalendarItems?portal=inwoners

Dus alleen GFT en PMD? Wanneer het klopt kan ik het vrij eenvoudig intergreren, anders moet ik nog even zoeken hoe ik alle data op kan halen. Ter info, voor mijnafvalwijzer krijg je namelijk allees in 1x terug voor het hele jaar.

[{"GarbageTypeCode":"GFT","GarbageType":"GFT","Date":"2021-01-28T00:00:00","Regular":true},{"GarbageTypeCode":"PMD","GarbageType":"PMD","Date":"2021-02-04T00:00:00","Regular":true},{"GarbageTypeCode":"GFT","GarbageType":"GFT","Date":"2021-02-11T00:00:00","Regular":true}]

**Comment by RefleCs** [comment]
Ja die info klopt. PMD, Papier en GFT.

**Comment by xirixiz** [comment]
Dan komt het helemaal goed 👍

**Comment by xirixiz** [comment]
Fixed! Rova has been added in release 5.2.9: https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/5.2.9
Ofcourse also available in HACS. Please let me know if it works properly and close the issue afterwards.

I solved it differently. I noticed Rova also has the exact same api as afvalwijzer available, saved me a lot of work :)

**Comment by xirixiz** [comment]
See the readme how to use Rova. The provider is "inzamelkalender.rova" for now. In a future release I`ll make this more pretty so only rova is required to be filled.

**Comment by RefleCs** [comment]
I'll test it today and let you know. Pretty new to Hass so need some time to get it working ;)

**Comment by xirixiz** [comment]
Sure, no problem. Use hacs and install release 5.3.0 with provider set to rova.
You could also browse my example/live config: https://github.com/xirixiz/my-hass-config

**Comment by xirixiz** [comment]
Link to HACS: https://hacs.xyz/

**Comment by RefleCs** [comment]
Hacs is allready running ;) That is how I found your plugin :)

It's slowly comming together. Also used to programming but sometimes it's finding the logic in the product that takes the time :)

**Comment by RefleCs** [comment]
It works! Thanks so much!

**Comment by RefleCs** [comment]
With the Auto-entities code in place. How can I provide custom images with that, the way you show in your screenshot?

**Comment by xirixiz** [comment]
I think you're looking for something like this for your lovelace config.

```/local verwijst``` naar ```<hass_home>/config/www/afvalwijzer```. De images kunnen gevonden worden in mijn hass_config:
https://github.com/xirixiz/my-hass-config

```yaml
  - cards:
      - entity: sensor.afvalwijzer_today_formatted
        show_name: false
        show_state: false
        state_image:
          GFT: /local/afvalwijzer/GFT.png
          Geen: /local/afvalwijzer/Geen.png
          PMD: /local/afvalwijzer/PMD.png
          Papier: /local/afvalwijzer/Papier.png
          Restafval: /local/afvalwijzer/Restafval.png
        type: picture-entity
      - entity: sensor.afvalwijzer_tomorrow_formatted
        show_name: false
        show_state: false
        state_image:
          GFT: /local/afvalwijzer/GFT.png
          Geen: /local/afvalwijzer/Geen.png
          PMD: /local/afvalwijzer/PMD.png
          Papier: /local/afvalwijzer/Papier.png
          Restafval: /local/afvalwijzer/Restafval.png
        type: picture-entity
      - entity: sensor.afvalwijzer_day_after_tomorrow_formatted
        show_name: false
        show_state: false
        state_image:
          GFT: /local/afvalwijzer/GFT.png
          Geen: /local/afvalwijzer/Geen.png
          PMD: /local/afvalwijzer/PMD.png
          Papier: /local/afvalwijzer/Papier.png
          Restafval: /local/afvalwijzer/Restafval.png
        type: picture-entity
    type: horizontal-stack
  - type: 'custom:auto-entities'
    card:
      type: glance
    filter:
      include:
        - entity_id: sensor.afvalwijzer_gft
        - entity_id: sensor.afvalwijzer_papier
        - entity_id: sensor.afvalwijzer_pmd
        - entity_id: sensor.afvalwijzer_restafval
    sort:
      attribute: days_until_collection_date
      method: attribute
      numeric: true
  - entities:
      - entity: sensor.afvalwijzer_next_item
      - entity: sensor.afvalwijzer_next_in_days
      - style:
          background: '#62717b'
          height: 1px
          margin-left: auto
          margin-right: auto
        type: divider
      - entity: input_boolean.waste_moved
      - entity: input_boolean.waste_reminder
    show_header_toggle: false
    type: entities
    state_color: false
type: vertical-stack
```
