### ISSUE TITLE
hidden: false still in the integration code

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#140]
## Version of the custom_component

5.3.3
## Configuration

```yaml
sensor:

  - platform: afvalwijzer
    provider: mijnafvalwijzer
    postal_code: !secret postcode
    street_number: !secret huisnummer
```
Add your logs here.
Nothing in the logs

## Describe the bug

seems the integrations still uses the deprecated `hidden:` configuration option, please see https://community.home-assistant.io/t/garbage-pickup-date-mijnafvalwijzer-nl-custom-component/34631/623 .

There are no errors, and all is working well, but maybe best to take that out of the code?

## Debug log

```text

Add your logs here.

```
Nothing in the logs

<img width="872" alt="Schermafbeelding 2021-05-15 om 17 57 08" src="https://user-images.githubusercontent.com/33354141/118791218-cb478800-b896-11eb-9261-93ccdd661405.png">
