### ISSUE TITLE
Sensor update issue

### ISSUE THREAD

**Issue by maxoss** [xirixiz/homeassistant-afvalwijzer#143]
## Version of the custom_component

2021.05.01
## Configuration

```yaml

sensor:

  - platform: afvalwijzer
    provider: mijnafvalwijzer
    postal_code: !secret postcode
    street_number: !secret huisnummer

```

## Describe the bug

sensor.afvalwijzer_today is not updating. It shows "geen" if it needs to show "papier" 

## Debug log

```text

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:692
Integration: Sensor (documentation, issues)
First occurred: 14 augustus 2021 18:24:29 (9914 occurrences)
Last logged: 21:31:10

Updating afvalwijzer sensor took longer than the scheduled update interval 0:00:30

```
