### ISSUE TITLE
Sensors not being created

### ISSUE THREAD

**Issue by JelleMarc** [xirixiz/homeassistant-afvalwijzer#154]
### Issue

Followed the instruction manual, however the sensor is not being created.
Double checked everything. Configuration.yaml:

``````````````
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:    
  themes: !include_dir_merge_named themes
  javascript_version: latest
homeassistant:
  customize: !include customize.yaml
light:
  - platform: group
    name: “Ganglampen Beneden”
    entities:
      - light.ganglamp_achter
      - light.ganglamp_voor
  - platform: afvalwijzer
    provider: mijnafvalwijzer
    postal_code: 1223AL
    street_number:  23
    suffix: ''
    include_date_today: true
    default_label: Geen
    id: ''
    exclude_list: ''

### Which version has the issue?

2021.11.02

### What was the last working version?

_No response_

### Anything in the logs that might be useful?

```txt
Nothing in the logs
```


### Additional information

_No response_
