### ISSUE TITLE
update mobile_app notifications

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#155]
### Request

Hi, since you're still using the 'legacy' iOS methods, I didnt want to PR just yet, but please let me suggest here you adapt you examples according to the modern companion app style?

using this myself:

```
      - service: notify.mobile_app_phone
        data:
          title: iOS notification
          message: >
            {{states('sensor.afvalwijzer_today')|title}} wordt vandaag opgehaald, zet het afval aan de straat
          data:
            actions:
              - action: MARK_TRASH_MOVED
                title: Afval verwerkt
                authenticationRequired: false
                activationMode: background
                destructive: true
            push:
              badge: 5
              # category: afval  # <--- take this out
              sound: US-EN-Morgan-Freeman-Cleaning-Supplies-Closet-Opened.wav
            action_data:
              entity_id: input_boolean.trash_outside
```

and 

```
  - alias: Mark trash as moved outside from notification
    id: Mark trash as moved outside from notification
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: MARK_TRASH_MOVED
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.trash_outside
      - service: persistent_notification.dismiss
        data:
          notification_id: >
            trash-notification-{{'today' if is_state('persistent_notification.trash_notification_today','notifying')
                                 else 'tomorrow'}}
      - service: notify.mobile_app_phone
        data:
          title: iOS notification
          message: >
            Afval staat aan de straat
          data:
            push:
              badge: 0
              sound: >
                {{'US-EN-Morgan-Freeman-Good-Morning.wav' if
                   states('sensor.part_of_day') in ['Morning','Afternoon']
                   else 'US-EN-Morgan-Freeman-Good-Night.wav'}}
```

maybe you could use the idea for you examples.

cheers!
