### ISSUE TITLE
Add meerlanden afvalkalender as source

### ISSUE THREAD

**Issue by adekloet** [xirixiz/homeassistant-afvalwijzer#160]
### Request

The muncipality I live changed to meerlanden as the waste collector. It has a website with postcode and number to see the waste collection days. Could meerlanden be added to the integration as source? 

https://inzamelkalender.meerlanden.nl/modules/800bf8d7-6dd1-4490-ba9d-b419d6dc8a45/kalender/

**Comment by xirixiz** [comment]
Hi Alex, do you have an example postal code and house number?

**Comment by xirixiz** [comment]
I`m planning to add more waste providers soon, as this is requested more frequently.

**Comment by adekloet** [comment]
> Hi Alex, do you have an example postal code and house number?

yes please check  2201 XZ 38
https://inzamelkalender.meerlanden.nl/modules/800bf8d7-6dd1-4490-ba9d-b419d6dc8a45/kalender/calendar.html?3000194029&Strandloper---38%20%20%20---2201XZ---Noordwijk---Noordwijk

Thanks Bram!

**Comment by adekloet** [comment]
I see there are options to get an connection via their API:

webcal://wasteprod2api.ximmio.com/api/CallIcal?cn=Meerlanden&x=800bf8d7-6dd1-4490-ba9d-b419d6dc8a45&ty=Noordwijk&ua=3000194029&sd=2021-12-21&ed=2025-01-09&path=https://wasteprod2api.ximmio.com&ln=nl&nt=7

and I see option to download calendars via f.i. iCal.

**Comment by xirixiz** [comment]
Working on it. Should be working somewhere at the end of this week. Also it provides me the flexibility to add more providers easily.

**Comment by adekloet** [comment]
> Working on it. Should be working somewhere at the end of this week. Also it provides me the flexibility to add more providers easily.

Thanks Bram sounds good, let me know if I need to test anything.

**Comment by xirixiz** [comment]
Dit werkt iig: 
```
curl -s 'https://wasteprod2api.ximmio.com/api/FetchAdress' -H 'content-type: application/json;charset=UTF-8' --data-raw '{ "postCode": "2201XZ", "houseNumber": "38", "companyCode": "800bf8d7-6dd1-4490-ba9d-b419d6dc8a45", "houseLetter":""}' | jq

```
curl -s 'https://wasteprod2api.ximmio.com/api/GetCalendar' -H 'content-type: application/json;charset=UTF-8' --data-raw '{"companyCode":"800bf8d7-6dd1-4490-ba9d-b419d6dc8a45","startDate":"2019-12-21","endDate":"2023-01-09","community":"Noordwijk","uniqueAddressID":"3000194029"}' | jq
```

Heb de eerste versie geschreven en ga het vanavond even testen.

**Comment by xirixiz** [comment]
Yes, de code is voor 80% gereed. De basis werkt goed. 
Nu nog de next sensors en sensoren voor morgen, overmorgen etc toevoegen. 
De code daarvoor is al herstructureerd, dus dat is mooi!

Ik  moet even kijken of het lukt, maar ergens de komende dagen is het wel klaar.

**Comment by adekloet** [comment]
Goed werk! Ik hou het in de gaten deze week.

**Comment by xirixiz** [comment]
Great news! Code is ready to test! Ofcourse I've perfomed some initial testing and everything should be fine.
However, I've learned from the past that sometimes things can be tricky! 😉

Please install the test branch on your system, set the parameters (one has changed, so you need to update your configuration)
This folder:
https://github.com/xirixiz/homeassistant-afvalwijzer/tree/test/custom_components/afvalwijzer

Needs to be in:
```<your hass folder>/config/custom_components/```

**Comment by adekloet** [comment]
> Great news! Code is ready to test! Ofcourse I've perfomed some initial testing and everything should be fine. However, I've learned from the past that sometimes things can be tricky! wink
> 
> Please install the test branch on your system, set the parameters (one has changed, so you need to update your configuration) This folder: https://github.com/xirixiz/homeassistant-afvalwijzer/tree/test/custom_components/afvalwijzer
> 
> Needs to be in: `<your hass folder>/config/custom_components/`
> 
> Please let me know whether it's also working properly for you so I can finalize a release.

Hi Bram,

Is there a way that I can clone it as zip? Then I can copy the files over to HA. They only way I see now is to copy every file separately, you can probably read from my question that I am not a GitHub master :-)

Thanks..

**Comment by xirixiz** [comment]
https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/2022.01.03-test

**Comment by xirixiz** [comment]
- next_item is nu next_type (aanpassing in de interface wellicht).
- include_date_today is nu exclude_pickup_today (indien je die al niet gebruikte of de default waarde hanteerde, dan wijzigt er niets)

**Comment by adekloet** [comment]
Cloned the files;

I looked in the source, change the provider to "meerlanden" for the test? I thgink thatis it right? The other values I used are default:

```
sensor:

  - platform: afvalwijzer
  #  provider: mijnafvalwijzer        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova
    provider: meerlanden
    postal_code: 2201XZ             # (required, default = '')
    street_number:  30                # (required, default = '')
    suffix: ''                       # (optional, default = '')
    include_date_today: false        # (optional, default = false) to take or not to take Today into account in the next pickup.
    default_label: Geen              # (optional, default = Geen) label if no date found
    id: ''                           # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
    exclude_list: ''                 # (optional, default = '') comma separated list of wast types (case ignored). F.e. "papier, gft"
```
