### ISSUE TITLE
attribute is_collection_date_today not correct.

### ISSUE THREAD

**Issue by TheFes** [xirixiz/homeassistant-afvalwijzer#161]
### Issue

Today it is the collection day for both christmas trees and dhm (had to look that up myself, it stands for `droog herbruikbaar materiaal` and is both paper and PMD)
The sensor `sensor.afvalwijzer_today` reflects that correctly with the state `kerstbomen, dhm`
However, the collection date for both related sensors is already updated, and therefor I can not use the attribute `is_collection_date_today`

The state of `sensor.afvalwijzer_dhm` is `21-01-2022` so that is 2 weeks from now. The attributes are:
```yaml
last_update: 07-01-2022 14:28
days_until_collection_date: 14
is_collection_date_today: false
is_collection_date_tomorrow: false
is_collection_date_day_after_tomorrow: false
year_month_day_date: 2022-01-21
icon: mdi:trash-can-outline
friendly_name: Papier en PMD
```

For `sensor.afvalwijzer_kerstbomen` this is similar, although there is no collection date known yet, so the state is `Geen`.

As there is an attribute `is_collection_date_today` I would expect that I'm able to actually use it :)

### Which version has the issue?

2021.12.1
