### ISSUE TITLE
Formate date

### ISSUE THREAD

**Issue by snhnic** [xirixiz/homeassistant-afvalwijzer#164]
### Issue

```
type: glance
entities:
  - entity: sensor.afvalwijzer_gft_2
    name: GFT
```
Hoe can I get to change the format of the time stamp? The year is not visible.

### Which version has the issue?

latest

**Comment by xirixiz** [comment]
Can you show the output of developer tools -> states - > sensor.afvalwijzer_gft
By default the year should be there:

![image](https://user-images.githubusercontent.com/11210639/149654107-0a3ae8f2-44d7-4de8-943d-35e3ed91cf74.png)

**Comment by xirixiz** [comment]
If you can share your postal code I can have a look if the data from the provider is valid.

**Comment by snhnic** [comment]
9607PA

`
last_update: 19-01-2022 09:43
days_until_collection_date: 14
is_collection_date_today: false
is_collection_date_tomorrow: false
is_collection_date_day_after_tomorrow: false
year_month_day_date: '2022-02-02'
icon: mdi:recycle
friendly_name: afvalwijzer gft
`

I like to see below the icon 02-02 but now see 02-02-2022

**Comment by xirixiz** [comment]
Ah, ok the other way around. This is something you have to do yourself I`m afraid. You can do so by creating a template sensor and changing the source to the format you'd like to see.

Something like this:

https://github.com/xirixiz/my-hass-config-obsolete/blob/301d334804860503b4d6502eec22ce441643e729/packages/trash.yaml#L59-L72

So:
```
- platform: template
    sensors:
      afvalwijzer_gft_formatted:
        entity_id: sensor.afvalwijzer_gft
        value_template: '{{ as_timestamp(strptime(states.sensor._gft.state, "%d-%m-%Y")) | timestamp_custom("%d %m") }}'
```

Then you can use sensor.afvalwijzer_gft_formatted in your frontend and the correct dat will be shown.
