### ISSUE TITLE
Afvalwijzer no longer working for Albrandswaard (BAR)

### ISSUE THREAD

**Issue by bolderbast** [xirixiz/homeassistant-afvalwijzer#219]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/xirixiz/homeassistant-afvalwijzer/blob/master/.github/SUPPORT.md)

### Description

As of today, the Afvalwijzer integration no longer works for Albrandswaard (BAR).
Seems they have switched to another calendar/partner:

https://www.bar-afvalbeheer.nl/afvalkalender-beschikbaar-in-nieuwe-app

They also have a new app: https://play.google.com/store/apps/details?id=nl.qubz21.burgerportaal.bar.prod

Hope this integration can be adjusted to accommodate for this change.

### Expected behaviour

Afvalwijzers sensors showing correct data

### Actual behaviour

Sensors showing none/unavailable

### Version

* HASS version: 2023.1.7
* Component version: 2023.01.01

### HASS logs

homeassistant  | 2023-02-01 17:23:05.434 ERROR (SyncWorker_10) [custom_components.afvalwijzer.const.const] Other error occurred _get_next_waste_date: list index out of range
homeassistant  | 2023-02-01 17:23:05.471 ERROR (SyncWorker_10) [custom_components.afvalwijzer.const.const] Other error occurred _get_next_waste_in_days: unsupported operand type(s) for -: 'datetime.datetime' and 'str'

**Comment by xirixiz** [comment]
I could have a look, but this seems completely new. Do you have a postal code for me?

**Comment by bolderbast** [comment]
Hi. It already was set to "bar", and it worked great for months (years?) until this week/yesterday.

This is the config I am using, and it does not work anymore, unfortunately:

```yaml
- platform: afvalwijzer
  provider: bar
  postal_code: 3171PT
  street_number:  <my house number, pick any odd number between 1 and 45 to test>
  suffix: ''
  exclude_pickup_today: false
  default_label: Geen
  id: ''
  exclude_list: ''
```

This report is to inform you that it broke since then. Maybe you were a bit too quick to close this issue? Can it be re-opened?

Other integrations also broke since then (https://github.com/heyajohnny/afvalinfo/issues/357), I believe yours also needs to be adjusted for then new data source.

Thanks.
