### ISSUE TITLE
Modernize Afvalwijzer to its own platform

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#267]
### Request

as per request, a separate FR for going forward

btw, I believe the next step would be to get the integration under its own platform
```
afvalwijzer:
  - provider: mijnafvalwijzer
    postal_code: !secret postcode
    street_number: !secret huisnummer
```
instead of
```
sensor:

  - platform: afvalwijzer
    provider: mijnafvalwijzer
    postal_code: !secret postcode
    street_number: !secret huisnummer
```
and maybe a first step towards that:
move all attributes to individual entities (which will be disabled by default, and only enabled upon user command). That way the integration would become more in alignment with modern HA guidelines, and probably also easier on the system (less attributes is smaller in the DB)

if this would go well, you could even consider creating a config flow, where users add the config settings in the UI, and take out the need for any yaml configuration completely.

you could have a look at WAQI, which was recently moved from yaml to UI, by Joost Lekkerkerker (at Joostlek). Im sure he would be willing to lend a hand ;-=)

or check out [Sun2 by Phil Bruckner](https://github.com/pnbruckner/ha-sun2), which also migrated recently, and still has some config in yaml, while all generic stuff is in the UI.

### Additional information

_Originally posted by @Mariusthvdb in https://github.com/xirixiz/homeassistant-afvalwijzer/issues/253#issuecomment-1890912428_
