### ISSUE TITLE
Dates not showing up in glance tiles

### ISSUE THREAD

**Issue by mariobrosch** [xirixiz/homeassistant-afvalwijzer#291]
### The problem

Since the last update I dont have dates in my card, but only textual visualisations. Please advice, because this doesnt help me anymore.

![image](https://github.com/xirixiz/homeassistant-afvalwijzer/assets/9047518/b4d6838d-926c-4382-834f-61885ebeb821)

```
- type: custom:auto-entities
    card:
      type: glance
    filter:
      include:
        - entity_id: sensor.afvalwijzer_gft
        - entity_id: sensor.afvalwijzer_papier
        - entity_id: sensor.afvalwijzer_pmd
        - entity_id: sensor.afvalwijzer_restafval
    sort:
      attribute: days_until_collection_date
      method: attribute
      numeric: true
```

How can I get back to displaying dates below the icons?

### Version of afvalwijzer integration having the issue?

2024.06.02

### Version of Home Assistant Core having the issue?

latest
