### ISSUE TITLE
thrash type entity state renders `Invalid data` in automation

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#345]
### The problem

using an automation based in state change I write that dat into the calendar. Up to 2024.12.0 this has always worked fine, but now I see below error.

still figuring out if this is user error (set up the wrong format in the config flow) or something changed in the actual entity state (output of the integration?)

### Version of afvalwijzer integration having the issue?

2024.12.02

### Version of Home Assistant Core having the issue?

2024.12.4

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.automation.afvalwijzer_in_calendar
Bron: helpers/script.py:2032
integratie: Automatisering (documentatie, problemen)
Eerst voorgekomen: 01:10:27 (1 gebeurtenissen)
Laatst gelogd: 01:10:27

automation 0: Error executing script. Invalid data for call_service at pos 2: Could not parse date for dictionary value @ data['start_date']
```

### Additional information

apparently the variable `date` can no longer be set based on the state, need to find out why that is.

maybe I set the wrong format (iso) as I can remember I had the simpler `2024-12-21` before 

<img width="1048" alt="Scherm­afbeelding 2024-12-19 om 07 52 06" src="https://github.com/user-attachments/assets/266ec809-345a-4ed0-aa14-04c442f33781" />

(can not reconfigure though as the config flow is borked)

```
automation:

  - id: afvalwijzer_in_calendar
    mode: queued
    triggers:
      trigger: state
      entity_id:
        - sensor.afvalwijzer_gft
        - sensor.afvalwijzer_papier
        - sensor.afvalwijzer_plastic
        - sensor.afvalwijzer_restafval
      not_to: geen
    conditions: []
    actions:
      - variables:
          date: >
            {{trigger.to_state.state}}
          soort: >
            {{trigger.to_state.attributes.friendly_name}}
      - action: calendar.create_event
        target:
          entity_id: calendar.afvalwijzer
        data:
          summary: >
            Ophaaldag Saver: {{soort}}
          description: >
            {{soort}}
          start_date: >
            {{date}}
          end_date: >
            {{(as_datetime(date) + timedelta(days=1))
               |as_timestamp|timestamp_custom('%Y-%m-%d')}}
```
