### ISSUE TITLE
How do i get the icons?

### ISSUE THREAD

**Issue by AfcaEric** [xirixiz/homeassistant-afvalwijzer#369]
### The problem

I'm at a loss. I completely removed and reinstalled it through HACS. Setup my provider (Saver) and the sensors are created perfectly, everything fine. But no matter what i do, i can't get the icons.

Manually placed icons in /www/afvwalwijzer. Restarted Home Assistant multiple times, but they don't show up.
I even tried to reverse engineer the code from your frontpage, but `type: custom:auto-entities` doesn't exist (anymore) i think?

```
- type: custom:auto-entities
  card:
    type: glance
  filter:
    exclude:
      - entity_id: sensor.afvalwijzer_*next*
      - entity_id: sensor.afvalwijzer_day_after_tomorrow*
      - entity_id: sensor.afvalwijzer_today*
      - entity_id: sensor.afvalwijzer_tomorrow*
      - entity_id: sensor.afvalwijzer_kerstbomen*
      - entity_id: sensor.afvalwijzer_*orgen
      - entity_id: sensor.afvalwijzer_van*
    include:
      - entity_id: sensor.afvalwijzer_*
        options:
          format: date
  sort:
    method: state
- entities:
    - style:
        background: '#62717b'
        height: 1px
        margin-left: auto
        margin-right: auto
      type: divider
  type: entities
- type: markdown
  content: >-
    <center>De volgende leging is {{ states('sensor.afvalwijzer_next_type')
    }}. Dat is over {{ states('sensor.afvalwijzer_next_in_days') }} {% if
    is_state('sensor.afvalwijzer_next_in_days', '1') %}dag{% else %}dagen{%
    endif %}.</center>
```

### Version of afvalwijzer integration having the issue?

2024.12.07

### Version of Home Assistant Core having the issue?

2024.12.5

**Comment by xirixiz** [comment]
The location of the icons seems to alright. However, they still need to be defined with something like this:

```
homeassistant:
  customize:
    sensor.afvalwijzer_today:
      friendly_name: Vandaag
    sensor.afvalwijzer_tomorrow:
      friendly_name: Morgen
    sensor.afvalwijzer_next_item:
      friendly_name: Next pickup item
    sensor.afvalwijzer_next_in_days:
      friendly_name: Next pickup in days
    input_boolean.waste_reminder:
      icon: mdi:reminder

    sensor.afvalwijzer_gft:
      friendly_name: GFT
      entity_picture: /local/afvalwijzer/GFT.png
    sensor.afvalwijzer_papier:
      friendly_name: Papier
      entity_picture: /local/afvalwijzer/Papier.png
    sensor.afvalwijzer_pmd:
      friendly_name: PMD
      entity_picture: /local/afvalwijzer/PMD.png
    sensor.afvalwijzer_restafval:
      friendly_name: Restafval
      entity_picture: /local/afvalwijzer/Restafval.png
```

Do you have something defined like that? Maybe you accidentaly removed it when you upgraded to the latest version (config_flow update).

**Comment by AfcaEric** [comment]
Thank you @xirixiz. I've never worked with customizing entities through configuration/customize.yaml, so i thought they were Icons and would show up in the same list as the MDI icons (after a reload).

It's fixed now:
![image](https://github.com/user-attachments/assets/ffc46da2-e6b2-4e98-8aad-49d06c085b95)

For anyone interested the full solution:

1. Make sure you have the .png's stored in `/www/afvalwijzer` (which can be referenced as just `/local`/)
2. Either configure the following in your `configuration.yaml` or create a `customize.yaml` and reference that in your `configuration.yaml` (i went with the first option)

```
homeassistant:
  customize:
    sensor.afvalwijzer_today:
      friendly_name: Vandaag
    sensor.afvalwijzer_tomorrow:
      friendly_name: Morgen
    sensor.afvalwijzer_next_item:
      friendly_name: Next pickup item
    sensor.afvalwijzer_next_in_days:
      friendly_name: Next pickup in days
    input_boolean.waste_reminder:
      icon: mdi:reminder

    sensor.afvalwijzer_gft:
      friendly_name: GFT
      entity_picture: /local/afvalwijzer/GFT.png
    sensor.afvalwijzer_papier:
      friendly_name: Papier
      entity_picture: /local/afvalwijzer/Papier.png
    sensor.afvalwijzer_pmd:
      friendly_name: PMD
      entity_picture: /local/afvalwijzer/PMD.png
    sensor.afvalwijzer_restafval:
      friendly_name: Restafval
      entity_picture: /local/afvalwijzer/Restafval.png
```
3. Reload HomeAssistant
4. If anyone wants the same custom card as xirixiz, [you should add this custom card through HACS](https://github.com/thomasloven/lovelace-auto-entities)
