### ISSUE TITLE
Provided lovelace code invalid when trying to import

### ISSUE THREAD

**Issue by RedFirebreak** [xirixiz/homeassistant-afvalwijzer#389]
### The problem

Hi there! Exactly as the title suggest. In the readme there's a great example of the sensor-widget i'm trying to import as a card on my dashboard. Preferably exactly like the screenshot.

![Image](https://github.com/user-attachments/assets/b565d320-5e1a-49b3-be81-cc918813229b)

Error code provided: "Cannot read properties of undefined". Unless im trying to import it wrong on my dashboard, are there any instructions im missing or is the provided lovelace-code invalid due to updates? 

Also, Maybe it would be nice to mention in the readme that the "auto-entities" HACS plugin is required :)

### Version of afvalwijzer integration having the issue?

2025.01.01

### Version of Home Assistant Core having the issue?

2025.2.0

### Anything in the logs that might be useful for us?

```txt
Installed literally today, fresh version of HACS / Home Assistant and the plugin
```

**Comment by Derksie** [comment]
I want to know aswell (new to homeassistant) tried the same

**Comment by PatrickSt1991** [comment]
@RedFirebreak  @Derksie I've just tested the code and it's working fine
```yaml
views:
  - title: Home
    cards:
      - type: custom:auto-entities
        card:
          type: glance
        filter:
          exclude:
            - entity_id: sensor.afvalwijzer_*next*
            - entity_id: sensor.afvalwijzer_day_after_tomorrow*
            - entity_id: sensor.afvalwijzer_today*
            - entity_id: sensor.afvalwijzer_tomorrow*
            - entity_id: sensor.afvalwijzer_kerstbomen*
            - entity_id: sensor.afvalwijzer_*orgen
            - entity_id: sensor.afvalwijzer_van*
          include:
            - entity_id: sensor.afvalwijzer_*
              options:
                format: date
        sort:
          method: state
      - entities:
          - style:
              background: '#62717b'
              height: 1px
              margin-left: auto
              margin-right: auto
            type: divider
        type: entities
      - type: markdown
        content: >-
          <center>De volgende leging is {{
          states('sensor.afvalwijzer_next_type') }}. Dat is over {{
          states('sensor.afvalwijzer_next_in_days') }} {% if
          is_state('sensor.afvalwijzer_next_in_days', '1') %}dag{% else
          %}dagen{% endif %}.</center>

```

![Image](https://github.com/user-attachments/assets/bac8b91e-2d16-4bb7-ab1d-25d8460714d4)

Do you have the plugin installed via HACS or any other way?

If you look in you Entities list and you search for **afvalwijzer** are there any returns?

![Image](https://github.com/user-attachments/assets/87624d1b-456d-4994-abc8-f7d420515474)
like this?

cause it sounds like the sensors are not existing and thats why it returns a null object
