### ISSUE TITLE
Sensors are reset every 1 hour

### ISSUE THREAD

**Issue by P-Verbrugge** [xirixiz/homeassistant-afvalwijzer#89]
I noticed through my automations that the sensors change every 1 hour. I have an automation that's sends me a message on my phone as soon as the sensor (trash tomorrow and trash today) changes.

However, I am getting a message every hour now. :-)

With version 4.8 this did not happen. So, it's only since the updated version that it changes. Is there any way that you can hold the status of the sensor it last had when you do a check and just change it, when the value received from the api is actually different compared to the sensor state?

**Comment by xirixiz** [comment]
That's great! At least you'll now never forget about any trash 😄 

I`ll look into it, but why would you send a notification on trash type change of a sensor?
Can you share the automation here?

I`m not sure what the difference is as 4.8 did also update/change the sensor every hour regardless of the value

**Comment by Mariusthvdb** [comment]
might be related:
after the latest updates, and on a todays pickup day, it shows fine, up to the moment the next day starts ;-) Check below GFT, which was the trash type. The sensor starts counting the hours passed.... while the todays image is still on (now yesterdays GFT)

![20200929_224515000_iOS](https://user-images.githubusercontent.com/33354141/94669789-fbdfaf00-0311-11eb-809c-70a129ed4654.jpg)

**Comment by xirixiz** [comment]
It seems today, tomorrow and day_after_tomorrow sensors aren't being updated properly. Those sensors currently don't show anything at all on my side (execept after a HASS restart). I`ll look into it.

![image](https://user-images.githubusercontent.com/11210639/94670954-870d7480-0313-11eb-838c-26aa0db262fe.png)

**Comment by Mariusthvdb** [comment]
sorry for this GitHub question, bathos can I resize the images in a post (compare your and my screenshot...)

**Comment by xirixiz** [comment]
Hehehe, not sure, I just create a screenshot ... and that just depends on the size of the screen.
Zoom out and create a screenshot makes things smaller :).

**Comment by xirixiz** [comment]
Oeps, I was still running on 5.0.0, so the sensor tomorrow wasn't showing properly 😛.

**Comment by P-Verbrugge** [comment]
> That's great! At least you'll now never forget about any trash 😄
> 
> I`ll look into it, but why would you send a notification on trash type change of a sensor?
> Can you share the automation here?
> 
> I`m not sure what the difference is as 4.8 did also update/change the sensor every hour regardless of the value

Here is my automation:
`
alias: general_trash_today_phone_push_notification
trigger:
  - platform: state
    entity_id: sensor.trash_today
condition: 
  - condition: template
    value_template: >-
      {{ states('sensor.trash_today') != 'Geen' }}
action:
  - service: script.telegram_message_push_notifcation
    data:
      title: "Afval"
      message: >-
        Vandaag: {{ states('sensor.trash_today') }}
`
"but why would you send a notification on trash type change of a sensor?". The reason is that I can see on my phone in the morning if I have to put out trash today/tomorrow and what kind of trash. That way I don't have to check the calendar and/or login into HA to check it. :-)

**Comment by xirixiz** [comment]
I think it is a typo on your end, try this.

The prefix changed from ```trash_``` to ```afvalwijzer_```

```
- alias: general_trash_today_phone_push_notification
  trigger:
    - platform: state
      entity_id: sensor.afvalwijzer_today
  condition:
    - condition: template
      value_template: >-
        {{ states('sensor.afvalwijzer_today') != 'Geen' }}
  action:
    - service: script.telegram_message_push_notifcation
      data:
        title: "Afval"
        message: >-
          Vandaag: {{ states('sensor.afvalwijzer_today') }}
```

**Comment by P-Verbrugge** [comment]
Whoops. I copied the wrong automation. It's from my backup system. :-D 
This is the correct one:
`alias: general_trash_today_phone_push_notification
trigger:
  - platform: state
    entity_id: sensor.afvalwijzer_today
condition: 
  - condition: template
    value_template: >-
      {{ states('sensor.afvalwijzer_today') != 'Geen' }}
action:
  - service: script.telegram_message_push_notifcation
    data:
      title: "Afval"
      message: >-
        Vandaag: {{ states('sensor.afvalwijzer_today') }}
`

My automation is setup with the new prefixes. However, I still receive it every one hour. It seems the state changes when the script does a check. At that moment my automation is triggered.

I have looked at your automation, but find it less elegant to be honest. Now you trigger the automation every hour every day, even when nothing changes. I prefer to execute the automation only when the state of the sensor changes. This worked up to version 4.8.

**Comment by Mariusthvdb** [comment]
yes, but wit this automation you will recieve a message at 00:35 in the night..... (or something close)
that's why I use:
```
  - alias: Afval vandaag
    id: Afval vandaag
    trigger:
      platform: time
      at: '07:00:00'
    condition:
      - >
          {{states.sensor.afvalwijzer_today is not none}}
      - >
          {{states('sensor.afvalwijzer_today') != 'Geen'}}
    action:
      - service: script.intercom_message
        data:
          message_nl: >
            Het is {{now().strftime('%A %-d %B')}}: vandaag wordt {{states('sensor.afvalwijzer_today')}} opgehaald!
          message_en: >
            It is {{now().strftime('%A %-d %B')}}: today {{states('sensor.afvalwijzer_today')}} will be collected!
      - service: script.notify_trash_today
      - service: script.persistent_trash_today
      - service: script.trash_outside_today
```
and for tomorrow in the evening (just like the Saver app):
```
  - alias: Afval morgen
    id: Afval morgen
    trigger:
      platform: time
      at: '21:00:00'
    condition:
      - >
          {{states.sensor.afvalwijzer_tomorrow is not none}}
      - >
          {{states('sensor.afvalwijzer_tomorrow') != 'Geen'}}
    action:
      - service: script.intercom_message
        data:
          message_nl: >
              Het is {{now().strftime('%d %B')}}: Morgen wordt
              {{states('sensor.afvalwijzer_tomorrow')|title}} opgehaald!
          message_en: >
              It is {{now().strftime('%d %B')}}: Tomorrow
              {{states('sensor.afvalwijzer_tomorrow')|title}} will be picked up!
      - service: script.notify_trash_tomorrow
      - service: script.persistent_trash_tomorrow
      - service: script.trash_outside_tomorrow
```
Seems cleanest this way, and always spot on

**Comment by P-Verbrugge** [comment]
@Mariusthvdb For me it doesn't matter how late I get the message. I will see it anyway when I unlock my phone. Will see if I can do something else with my automation I guess.

**Comment by xirixiz** [comment]
![image](https://user-images.githubusercontent.com/11210639/94717197-45e78580-0350-11eb-836b-8d50e0569cd0.png)

I just checked with the latest release and the sensor was last updated at the last restart, so I guess it should be fine. Can you verify?

**Comment by P-Verbrugge** [comment]
Ok, turned on the automation. Will keep an eye on it and report back. :-)

**Comment by P-Verbrugge** [comment]
Hmmm, have to look further into it. Automation is still triggered. 

Perhaps it’s a HA issue. Says the last update was at 21:22. However, the indicator in top says it was 2 hours ago.

![5FACE4F5-9BAD-4426-A348-92EBAD62F0B0](https://user-images.githubusercontent.com/41943098/94730536-a9c77980-0363-11eb-8116-543988d0fc81.jpeg)

**Comment by Mariusthvdb** [comment]
Did you add the condition I suggested ?

**Comment by P-Verbrugge** [comment]
> Did you add the condition I suggested ?

Just added it to my test setup and see what it does. From what I see it will not work. I already have a condition added to it. It fires because the condition is true.

It seems like that when the sensor get's update, even though the state does not change, the automation get's triggered by a state change. That's weird. I can always add a from condition to that when it changes from none/geen to a new state. But in the rare case that trash will be collected two days in a row, the trigger and condition will fail.

**Comment by Mariusthvdb** [comment]
that's not weird, it is to be expected. As you know. platform: state triggers [on all state changes, so also on attributes changes](https://www.home-assistant.io/docs/automation/trigger/#state-trigger), or even on the unavailability of the sensor, which might occur unexpectedly in the backend.

to guard all these events, the extra condition I suggested was made, and I always call it 'the One Condition to rule them all'.

we can't live without it.

**Comment by xirixiz** [comment]
The component is working fine and isn't updating the state, I just checked it again this morning. The only thing, but I`m totally not sure of, could be I've added the last_update attribute, that wasn't there before, and that is updating every time when the sensors have been verified/checked. Maybe you can compare this date/timestamp with the time you receive a notification.

**Comment by xirixiz** [comment]
Thanks Marius, I didn't read your post, but I guess the last_update attribute is causing this indeed. This could work for you

```
  trigger:
    platform: state
    entity_id: device_tracker.adam
  condition:
    platform: template
    value_template: '{{ trigger.to_state.state <> trigger.from_state.state }}
```

But then again, maybe a time based condition or triggger would suit better here.
